env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
  - 'eslint-config-prettier'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
globals: {
  "defineProps": "readonly",
  "defineEmits": "readonly",
  "defineExpose": "readonly",
  "withDefaults": "readonly"
}